db.url = jdbc:mariadb://localhost:3306/trip_calculator
# To run the application through Docker container, remove/comment the URL above and uncomment the URL below.#
# db.url = jdbc:mariadb://host.docker.internal:3306/trip_calculator

# Replace these with your MariaDB root user credentials:
db.rootUser = root
db.rootPassword = rootPassword
