sonar.projectKey = trip_calculator_sonar
sonar.projectName = trip_calculator
sonar.projectVersion = 1.0
sonar.sources = src
sonar.java.binaries = target/classes
sonar.host.url = http://localhost:9000
# If you add the token in user variable in Edit System Environment you do not need to mention
#sonar.token= squ_36ddcb7129eea21de9e6ef95dd0081b14220ecce
# run with:
#    mvn clean verify sonar:sonar "-Dsonar.projectKey=untitled" "-Dsonar.token=$env:SONAR_TOKEN" "-Dsonar.host.url=http://localhost:9000"